INFO[2023-05-09 13:04:25,204]: Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
INFO[2023-05-09 13:04:25,204]: Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
INFO[2023-05-09 13:04:25,207]: Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
INFO[2023-05-09 13:04:25,207]: Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
WARNING[2023-05-09 13:04:25,207]: No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
SIMBA SAFETY LOAD DEBUG:	 get_args
4 i
good login of ./SIMBA_jobstatus.dat in get_args
JOB STARTING
---------------------------------
Input urls:
	 .Data/data_shuffle/23-08-80/cont.dat
	 .Data/data_shuffle/23-08-80/line1.dat
	 .Data/data_shuffle/23-08-80/line2.dat
Traceback (most recent call last):
  File "/data/uqhmcdou/HM_Lag_Recovery/LineFit01.py", line 137, in <module>
    main()
  File "/data/uqhmcdou/HM_Lag_Recovery/LineFit01.py", line 64, in main
    cont  = array_to_lc(np.loadtxt(job_args["cont_url"]))
  File "/home/uqhmcdou/.conda/envs/lag_conda/lib/python3.10/site-packages/numpy/lib/npyio.py", line 1042, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/uqhmcdou/.conda/envs/lag_conda/lib/python3.10/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/uqhmcdou/.conda/envs/lag_conda/lib/python3.10/site-packages/numpy/lib/_datasource.py", line 529, in open
    return _file_openers[ext](found, mode=mode,
FileNotFoundError: [Errno 2] No such file or directory: '.Data/data_shuffle/23-08-80/cont.dat'
