Traceback (most recent call last):
  File "/home/uqhmcdou/.conda/envs/lag_conda/lib/python3.10/site-packages/numpyro/contrib/nested_sampling.py", line 10, in <module>
    from jaxns import (
  File "/home/uqhmcdou/.conda/envs/lag_conda/lib/python3.10/site-packages/jaxns/__init__.py", line 8, in <module>
    from jaxns.nested_sampler import *
  File "/home/uqhmcdou/.conda/envs/lag_conda/lib/python3.10/site-packages/jaxns/nested_sampler.py", line 6, in <module>
    from etils.array_types import PRNGKey, IntArray
  File "/home/uqhmcdou/.conda/envs/lag_conda/lib/python3.10/site-packages/etils/array_types/__init__.py", line 23, in <module>
    from etils import enp
  File "/home/uqhmcdou/.conda/envs/lag_conda/lib/python3.10/site-packages/etils/enp/__init__.py", line 31, in <module>
    from etils.enp.checking import check_and_normalize_arrays
  File "/home/uqhmcdou/.conda/envs/lag_conda/lib/python3.10/site-packages/etils/enp/checking.py", line 28, in <module>
    from etils.enp import type_parsing
  File "/home/uqhmcdou/.conda/envs/lag_conda/lib/python3.10/site-packages/etils/enp/type_parsing.py", line 26, in <module>
    import typing_extensions  # TODO(py38): Remove
ModuleNotFoundError: No module named 'typing_extensions'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/uqhmcdou/HM_Lag_Recovery/LineFit01.py", line 16, in <module>
    from fitting_procedure import fit_single_source
  File "/data/uqhmcdou/HM_Lag_Recovery/fitting_procedure.py", line 19, in <module>
    from numpyro.contrib.nested_sampling import NestedSampler
  File "/home/uqhmcdou/.conda/envs/lag_conda/lib/python3.10/site-packages/numpyro/contrib/nested_sampling.py", line 23, in <module>
    raise ImportError(
ImportError: To use this module, please install `jaxns` package. It can be installed with `pip install jaxns` with python>=3.8
